### ISSUE TITLE
Content by CFI

### ISSUE THREAD

**Issue by jbmeerkat** [KitaitiMakoto/epub-parser#11]
Hi, Kitaiti!
Can I get book fragment by CFI using your gem?

**Comment by KitaitiMakoto** [comment]
Hi, @jbmeerkat . Thank you for your interest in my library.
No, you cannot do that using only this gem for now although I intend to implement the feature in the future.

But you can it by combining this gem with [Nokogiri][] and [Nokogiri::XML::Range][]. I added a rough example in examples directory: https://github.com/KitaitiMakoto/epub-parser/blob/master/examples/exctract-content-using-cfi.rb
You can see how to prepare and try the example at the top of the file. I know it is not smart, has some limitation(such as HTML structure) and bugs, but it works anyway.
I hope it helps you.

Feel free to ask more questions and if you provide more details about your work, I might help you.

[Nokogiri]: http://www.nokogiri.org/
[Nokogiri::XML::Range]: https://github.com/KitaitiMakoto/nokogiri-xml-range

**Comment by jbmeerkat** [comment]
Thank you for the example @KitaitiMakoto !

I think you can close this issue.

**Comment by KitaitiMakoto** [comment]
Thanks!
