### ISSUE TITLE
How to extract main text without images and tables of content?

### ISSUE THREAD

**Issue by Immortalin** [KitaitiMakoto/epub-parser#13]
If one wants to extract the main text from a epub file i.e. without table of content or images and image captions etc. just the main prose, how should one do it?

**Comment by KitaitiMakoto** [comment]
@Immortalin 

tl;dr
```ruby
require 'epub/parser'

book = EPUB::Parser.parse('path/to/book.epub')
book.each_page_on_spine do |page|
  next unless page.xhtml?
  next if page.nav?

  xhtml = page.read
  doc = Nokogiri.XML(xhtml)
  puts doc.content
end
```

If you know about:

* EPUB structure
* HTML scraping library such as [Nokogiri][]

script above should make sense. If not, feel free to ask more questions.

If you know how to work with EPUB item(`page` in example)s, see http://www.rubydoc.info/gems/epub-parser/file/docs/Item.markdown

Nokogiri: http://www.nokogiri.org/

**Comment by Immortalin** [comment]
@KitaitiMakoto thank you for your quick reply! Is there a way to add up all the words in the doc.content? I tried using `book.each_page_on_spine.reduce` but it doesn't really work. Since code in ruby block cannot affect outside variables, is there any way of adding up the total word count of each page? i.e. `doc.content.split.size`?

**Comment by KitaitiMakoto** [comment]
@Immortalin 
> Since code in ruby block cannot affect outside variables

A block can access to outside variables when they are declared before the block begins:

```ruby
require "epub/parser"

book = EPUB::Parser.parse("path/to/book.epub")

whole = ""
book.each_page_on_spine do |page|
  next unless page.xhtml?
  next if page.nav?

  xhtml = page.read
  doc = Nokogiri.XML(xhtml)
  whole << doc.content
end
puts whole # => output whole content in a book
```

You can also use a number as a outside variable. If you need word count, it might be better:

```ruby
words = 0
book.each_page_on_spine do |page|
  next unless page.xhtml?
  next if page.nav?

  doc = Nokogiri.XML(page.read)
  words_in_page = doc.content.split(/\s+/)
  words += words_in_page.length
end
puts words # => 2802, for example
```

You can do the same thing by `reduce`, but declaring variables before blocks is a good start point.

**Comment by Immortalin** [comment]
@KitaitiMakoto thank you :D

**Comment by Immortalin** [comment]
@KitaitiMakoto I am trying to remove the cover page. I obtained the URI via `book.guide.cover.href` but I am not sure how exactly to remove it. i.e. what I am trying to do is  within 
```ruby 
book.each_page_on_spine do |page|
    next if page.cover?
end 
```

**Comment by KitaitiMakoto** [comment]
EPUB Parser doesn't have API for that. But because [EPUB::Publication::Package::Guide::Reference][Reference] has API that returns referenced `Item`, you can remove cover by using it:

```ruby
cover = book.guide.cover.item
book.each_page_on_spine do |page|
  next if page == cover
  # do something with page
end
```

[Reference]: http://www.rubydoc.info/gems/epub-parser/EPUB/Publication/Package/Guide/Reference
